import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox"] });
const p = await b.newPage({ viewport:{width:1180,height:980}, deviceScaleFactor: 1.5 });
await p.route("**/*", (r) => (/127\.0\.0\.1|localhost/.test(r.request().url()) ? r.continue() : r.abort()));
await p.goto("http://127.0.0.1:4173", { waitUntil: "domcontentloaded" });
await p.evaluate(() => { try { localStorage.setItem("ottoman.install-hint","true"); localStorage.setItem("ottoman.push-asked","true"); } catch {} });
await p.reload({ waitUntil: "domcontentloaded" });
await p.waitForTimeout(1800);
await p.evaluate(() => document.querySelector('button[title="Admin"]')?.click());
await p.waitForTimeout(1600);
await p.evaluate(() => [...document.querySelectorAll(".admin-tabs button")].find(x => x.innerText.trim() === "Bankalar")?.click());
await p.waitForTimeout(800);
await p.screenshot({ path: "shots/admin-banka.png" });
await p.evaluate(() => [...document.querySelectorAll(".admin-tabs button")].find(x => x.innerText.trim() === "Müşteriler")?.click());
await p.waitForTimeout(700);
await p.evaluate(() => document.querySelectorAll(".ac-list .ac-line")[0]?.click());
await p.waitForTimeout(1400);
await p.screenshot({ path: "shots/admin-musteri.png" });
await b.close();
console.log("cekildi");
