import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome", args: ["--no-sandbox"] });
const q = await b.newPage({ viewport:{width:820,height:1040}, deviceScaleFactor:1.6 });
await q.route("**/*", (r) => (/127\.0\.0\.1|localhost/.test(r.request().url()) ? r.continue() : r.abort()));
await q.goto("http://127.0.0.1:4173", { waitUntil: "domcontentloaded" });
await q.evaluate(() => { try { localStorage.setItem("ottoman.install-hint","true"); localStorage.setItem("ottoman.push-asked","true"); } catch {} });
await q.reload({ waitUntil: "domcontentloaded" });
await q.waitForTimeout(1600);
console.log("admin dugmesi:", await q.evaluate(() => Boolean(document.querySelector('button[title="Admin"]'))));
await q.evaluate(() => document.querySelector('button[title="Admin"]')?.click());
await q.waitForTimeout(1700);
await q.evaluate(() => [...document.querySelectorAll(".admin-tabs button")].find(x => x.innerText.trim() === "Bankalar")?.click());
await q.waitForTimeout(900);
await q.screenshot({ path: "shots/admin-banka2.png" });
await q.evaluate(() => document.querySelector(".bk-duzenle")?.click());
await q.waitForTimeout(800);
await q.screenshot({ path: "shots/admin-banka-duzenle.png" });
await q.close();
await b.close();
console.log("cekildi");
